# Copyright (c) 2026 ivfzhou
# ipasigner is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#          http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.

set(PUGIXML_NAME pugixml)
set(PUGIXML_LIBRARY_NAME pugixml.lib)
set(PUGIXML_HEADER_NAME pugixml.hpp)
set(PUGIXML_DIRECTORY ${DEPENDENCIES_DIRECTORY}/pugixml)
set(PUGIXML_INSTALL_DIRECTORY ${PUGIXML_DIRECTORY}/install)
set(PUGIXML_LIBRARY_DIRECTORY ${PUGIXML_INSTALL_DIRECTORY}/lib)
set(PUGIXML_HEADERS_DIRECTORY ${PUGIXML_INSTALL_DIRECTORY}/include)

find_library(
        PUGIXML_LIBRARY
        NAMES ${PUGIXML_LIBRARY_NAME}
        PATHS ${PUGIXML_LIBRARY_DIRECTORY}
        NO_DEFAULT_PATH
)

find_path(
        PUGIXML_INCLUDE_DIRECTORY
        NAMES ${PUGIXML_HEADER_NAME}
        PATHS ${PUGIXML_HEADERS_DIRECTORY}
        NO_DEFAULT_PATH
)

if (PUGIXML_LIBRARY AND PUGIXML_INCLUDE_DIRECTORY)
    message(STATUS "found pugixml library ${PUGIXML_LIBRARY}")
    message(STATUS "found pugixml include directory ${PUGIXML_INCLUDE_DIRECTORY}")
else ()
    include(ExternalProject)
    set(PUGIXML_BUILD_DIRECTORY ${PUGIXML_DIRECTORY}/build)
    set(PUGIXML_SOURCE_DIRECTORY ${PUGIXML_DIRECTORY}/source)
    ExternalProject_Add(
            ${PUGIXML_NAME}
            PREFIX ${PUGIXML_DIRECTORY}
            URL ${PUGIXML_URL}
            URL_HASH SHA256=${PUGIXML_SHA256}
            SOURCE_DIR ${PUGIXML_SOURCE_DIRECTORY}
            BINARY_DIR ${PUGIXML_BUILD_DIRECTORY}
            CONFIGURE_COMMAND ${CMAKE_COMMAND} --fresh -S ${PUGIXML_SOURCE_DIRECTORY} -B ${PUGIXML_BUILD_DIRECTORY}
                -DCMAKE_INSTALL_PREFIX=${PUGIXML_INSTALL_DIRECTORY}
                -DCMAKE_CONFIGURATION_TYPES=${CMAKE_BUILD_TYPE}
                -DCMAKE_MSVC_RUNTIME_LIBRARY=${CMAKE_MSVC_RUNTIME_LIBRARY}
                -DCMAKE_CXX_FLAGS_RELEASE=${LIBRARY_CXX_FLAGS_RELEASE}
                -DCMAKE_CXX_FLAGS_DEBUG=${LIBRARY_CXX_FLAGS_DEBUG}
            BUILD_COMMAND ${CMAKE_COMMAND} --build ${PUGIXML_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --parallel --clean-first
            INSTALL_COMMAND ${CMAKE_COMMAND} --build ${PUGIXML_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --target install
    )
    set(PUGIXML_LIBRARY ${PUGIXML_LIBRARY_DIRECTORY}/${PUGIXML_LIBRARY_NAME})
    set(PUGIXML_INCLUDE_DIRECTORY ${PUGIXML_HEADERS_DIRECTORY})
    list(APPEND DEPENDENCIES ${PUGIXML_NAME})
    unset(PUGIXML_BUILD_DIRECTORY)
    unset(PUGIXML_SOURCE_DIRECTORY)
endif ()

list(APPEND INCLUDES ${PUGIXML_INCLUDE_DIRECTORY})
list(APPEND LIBRARIES ${PUGIXML_LIBRARY})

unset(PUGIXML_LIBRARY_NAME)
unset(PUGIXML_HEADER_NAME)
unset(PUGIXML_DIRECTORY)
unset(PUGIXML_INSTALL_DIRECTORY)
unset(PUGIXML_LIBRARY_DIRECTORY)
unset(PUGIXML_HEADERS_DIRECTORY)
