# Copyright (c) 2026 ivfzhou
# ipasigner is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#          http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.

set(ZSTD_NAME zstd)
set(ZSTD_HEADER_NAME zstd.h)
set(ZSTD_LIBRARY_NAME zstd_static.lib)
set(ZSTD_DIRECTORY ${DEPENDENCIES_DIRECTORY}/zstd)
set(ZSTD_INSTALL_DIRECTORY ${ZSTD_DIRECTORY}/install)
set(ZSTD_LIBRARY_DIRECTORY ${ZSTD_INSTALL_DIRECTORY}/lib)
set(ZSTD_HEADERS_DIRECTORY ${ZSTD_INSTALL_DIRECTORY}/include)

find_library(
        ZSTD_LIBRARY
        NAMES ${ZSTD_LIBRARY_NAME}
        PATHS ${ZSTD_LIBRARY_DIRECTORY}
        NO_DEFAULT_PATH
)

find_path(
        ZSTD_INCLUDE_DIRECTORY
        NAMES ${ZSTD_HEADER_NAME}
        PATHS ${ZSTD_HEADERS_DIRECTORY}
        NO_DEFAULT_PATH
)

if (ZSTD_LIBRARY AND ZSTD_INCLUDE_DIRECTORY)
    message(STATUS "found zstd library ${ZSTD_LIBRARY}")
    message(STATUS "found zstd include directory ${ZSTD_INCLUDE_DIRECTORY}")
else ()
    include(ExternalProject)
    set(ZSTD_BUILD_DIRECTORY ${ZSTD_DIRECTORY}/build)
    set(ZSTD_SOURCE_DIRECTORY ${ZSTD_DIRECTORY}/source)
    ExternalProject_Add(
            ${ZSTD_NAME}
            PREFIX ${ZSTD_DIRECTORY}
            URL ${ZSTD_URL}
            URL_HASH SHA256=${ZSTD_SHA256}
            SOURCE_DIR ${ZSTD_SOURCE_DIRECTORY}
            BINARY_DIR ${ZSTD_BUILD_DIRECTORY}
            CONFIGURE_COMMAND ${CMAKE_COMMAND} --fresh -S ${ZSTD_SOURCE_DIRECTORY}/build/cmake -B ${ZSTD_BUILD_DIRECTORY}
                -DCMAKE_INSTALL_PREFIX=${ZSTD_INSTALL_DIRECTORY}
                -DCMAKE_CONFIGURATION_TYPES=${CMAKE_BUILD_TYPE}
                -DCMAKE_MSVC_RUNTIME_LIBRARY=${CMAKE_MSVC_RUNTIME_LIBRARY}
                -DCMAKE_C_FLAGS_RELEASE=${LIBRARY_C_FLAGS_RELEASE}
                -DCMAKE_C_FLAGS_DEBUG=${LIBRARY_C_FLAGS_DEBUG}
                -DCMAKE_CXX_FLAGS_RELEASE=${LIBRARY_CXX_FLAGS_RELEASE}
                -DCMAKE_CXX_FLAGS_DEBUG=${LIBRARY_CXX_FLAGS_DEBUG}
                -DZSTD_BUILD_TESTS=OFF
            BUILD_COMMAND ${CMAKE_COMMAND} --build ${ZSTD_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --parallel --clean-first
            INSTALL_COMMAND ${CMAKE_COMMAND} --build ${ZSTD_BUILD_DIRECTORY} --config ${CMAKE_BUILD_TYPE} --target install
    )
    set(ZSTD_LIBRARY ${ZSTD_LIBRARY_DIRECTORY}/${ZSTD_LIBRARY_NAME})
    set(ZSTD_INCLUDE_DIRECTORY ${ZSTD_HEADERS_DIRECTORY})
    list(APPEND DEPENDENCIES ${ZSTD_NAME})
    unset(ZSTD_BUILD_DIRECTORY)
    unset(ZSTD_SOURCE_DIRECTORY)
endif ()

list(APPEND INCLUDES ${ZSTD_INCLUDE_DIRECTORY})
list(APPEND LIBRARIES ${ZSTD_LIBRARY})

unset(ZSTD_HEADER_NAME)
unset(ZSTD_LIBRARY_NAME)
unset(ZSTD_DIRECTORY)
unset(ZSTD_INSTALL_DIRECTORY)
unset(ZSTD_LIBRARY_DIRECTORY)
unset(ZSTD_HEADERS_DIRECTORY)
